version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Bitrise CLI
          command: bash ./install_bitrise_cli.sh
      - run:
          name: Bitrise Run primary workflow
          command: bitrise run primary
