version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: apt install wget
          command: apt update && apt install -y wget git
      - run:
          name: Install Bitrise CLI
          command: bash ./install_bitrise_cli.sh
      - run:
          name: Bitrise Run primary workflow
          command: bitrise run primary
